//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManiaX.Beacons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManiaX.Beacons.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter console command line to run tests : .
        /// </summary>
        internal static string Config_NUnitConsoleArgumentDescription {
            get {
                return ResourceManager.GetString("Config_NUnitConsoleArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter command to run tests via console runner.
        /// </summary>
        internal static string Config_NUnitConsoleArgumentsNotSpecified {
            get {
                return ResourceManager.GetString("Config_NUnitConsoleArgumentsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter test results folder : .
        /// </summary>
        internal static string Config_NUnitGuiArgumentDescription {
            get {
                return ResourceManager.GetString("Config_NUnitGuiArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter path to folder containing NUnit test results.
        /// </summary>
        internal static string Config_NUnitGuiArgumentsNotSpecified {
            get {
                return ResourceManager.GetString("Config_NUnitGuiArgumentsNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder does not exist..
        /// </summary>
        internal static string Config_TestResultsFolderDoesNotExist {
            get {
                return ResourceManager.GetString("Config_TestResultsFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all beacons.
        /// </summary>
        internal static string Main_PauseAllBeacons {
            get {
                return ResourceManager.GetString("Main_PauseAllBeacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume all beacons.
        /// </summary>
        internal static string Main_ResumeAllBeacons {
            get {
                return ResourceManager.GetString("Main_ResumeAllBeacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch hats.
        /// </summary>
        internal static string RB_ChangeHats {
            get {
                return ResourceManager.GetString("RB_ChangeHats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be having some trouble fixing your compile errors. Try reverting all your changes to a good build and taking smaller steps this time..
        /// </summary>
        internal static string SB_EnteredBrokenBuildsRutAdvisory {
            get {
                return ResourceManager.GetString("SB_EnteredBrokenBuildsRutAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be having some trouble getting all your tests to pass. It might be helpful to revert all changes to a green build, take a break and retry..
        /// </summary>
        internal static string SB_EnteredBrokenTestsRutAdvisory {
            get {
                return ResourceManager.GetString("SB_EnteredBrokenTestsRutAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phew! Good work getting the code to compile. Remember - Baby steps!.
        /// </summary>
        internal static string SB_LeftBrokenBuildsRutAdvisory {
            get {
                return ResourceManager.GetString("SB_LeftBrokenBuildsRutAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice! We&apos;re green again. Remember - Baby Steps!.
        /// </summary>
        internal static string SB_LeftBrokenTestsRutAdvisory {
            get {
                return ResourceManager.GetString("SB_LeftBrokenTestsRutAdvisory", resourceCulture);
            }
        }
    }
}
